In [2]:
import pandas as pd

In [128]:
df = pd.DataFrame()

In [129]:
df = pd.read_csv(r'C:\Users\harip\Downloads\traffic_stops.csv',low_memory=False)

# Drop columns with all missing values

In [121]:
df.dropna(axis=1, how='all', inplace=True)

In [127]:
df.head(10)

,stop_date,stop_time,country_name,driver_gender,driver_age,driver_race,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,1900-01-01 00:00:00,Canada,M,19,Asian,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,1900-01-01 00:01:00,India,M,58,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,1900-01-01 00:02:00,USA,M,76,Black,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,1900-01-01 00:03:00,Canada,M,76,Black,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,1900-01-01 00:04:00,Canada,M,75,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
5,2020-01-01,1900-01-01 00:05:00,Canada,F,73,Other,Other,True,Vehicle Search,Ticket,False,16-30 Min,False,MH89ZF7676
6,2020-01-01,1900-01-01 00:06:00,USA,F,70,White,Speeding,False,Vehicle Search,Ticket,False,30+ Min,False,KA40AD3153
7,2020-01-01,1900-01-01 00:07:00,India,M,50,Asian,Other,False,No Search,Arrest,True,30+ Min,True,DL75KZ7835
8,2020-01-01,1900-01-01 00:08:00,USA,F,30,Hispanic,Seatbelt,True,Frisk,Arrest,False,0-15 Min,True,DL50PO5101
9,2020-01-01,1900-01-01 00:09:00,USA,M,21,Asian,Signal,True,No Search,Warning,True,16-30 Min,False,KA79RD2271

In [130]:
df.isna().sum()

stop_date                 0
stop_time                 0
country_name              0
driver_gender             0
driver_age_raw            0
driver_age                0
driver_race               0
violation_raw             0
violation                 0
search_conducted          0
search_type           21720
stop_outcome              0
is_arrested               0
stop_duration             0
drugs_related_stop        0
vehicle_number            0
dtype: int64

Fill missing Values --- Handle NaN values

In [131]:
df.loc [(df['search_type'].isnull()), 'search_type'] = 'No Search'

DROP SPECFIC COLUMNS

In [132]:
df.drop(['violation_raw','driver_age_raw'],axis=1,inplace=True)

In [133]:
df.columns

Index(['stop_date', 'stop_time', 'country_name', 'driver_gender', 'driver_age',
       'driver_race', 'violation', 'search_conducted', 'search_type',
       'stop_outcome', 'is_arrested', 'stop_duration', 'drugs_related_stop',
       'vehicle_number'],
      dtype='object')

save the cleaned data

In [165]:
df.to_csv(r'D:\Traffic police project\cleaned_traffic_stop.csv',index=False) #Tells pandas not to include the row index in the CSV file (just the data columns).

In [142]:
df.dtypes

stop_date             datetime64[ns]
stop_time                     object
country_name                  object
driver_gender                 object
driver_age                     int64
driver_race                   object
violation                     object
search_conducted                bool
search_type                   object
stop_outcome                  object
is_arrested                     bool
stop_duration                 object
drugs_related_stop              bool
vehicle_number                object
dtype: object

convert to date - time format for stop_date and stop_time column

In [ ]:
#df['stop_date']=pd.to_datetime(df['stop_date'])
#df['stop_time'] = pd.to_datetime(df['stop_time'], format='%H:%M:%S', errors='coerce').dt.time

So i have to convert the datetime back to object for combining both the coloumns

In [158]:
df['stop_date'] = pd.to_datetime(df['stop_date']).dt.date

Combining to col to convert to date time data type from object

In [163]:
import pandas as pd

df['timestamp'] = df.apply(lambda row: pd.Timestamp.combine(row['stop_date'], row['stop_time']), axis=1)

In [183]:
df.dtypes

stop_date                     object
stop_time                     object
country_name                  object
driver_gender                 object
driver_age                     int64
driver_race                   object
violation                     object
search_conducted                bool
search_type                   object
stop_outcome                  object
is_arrested                     bool
stop_duration                 object
drugs_related_stop              bool
vehicle_number                object
timestamp             datetime64[ns]
dtype: object

LOADING THE CLEANED DATA

In [166]:
df = pd.read_csv(r'D:\Traffic police project\cleaned_traffic_stop.csv',low_memory=False)

In [167]:
df.head(5)

,stop_date,stop_time,country_name,driver_gender,driver_age,driver_race,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number,timestamp
0,2020-01-01,00:00:00,Canada,M,19,Asian,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473,2020-01-01 00:00:00
1,2020-01-01,00:01:00,India,M,58,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441,2020-01-01 00:01:00
2,2020-01-01,00:02:00,USA,M,76,Black,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264,2020-01-01 00:02:00
3,2020-01-01,00:03:00,Canada,M,76,Black,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807,2020-01-01 00:03:00
4,2020-01-01,00:04:00,Canada,M,75,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305,2020-01-01 00:04:00

In [168]:
df.columns

Index(['stop_date', 'stop_time', 'country_name', 'driver_gender', 'driver_age',
       'driver_race', 'violation', 'search_conducted', 'search_type',
       'stop_outcome', 'is_arrested', 'stop_duration', 'drugs_related_stop',
       'vehicle_number', 'timestamp'],
      dtype='object')

Connecting Mysql Database

In [169]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\harip\anaconda3\lib\site-packages (9.4.0)
Note: you may need to restart the kernel to use updated packages.

In [170]:
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",       # or your server IP
    user="root",            # your MySQL username
    password="1994",        # your MySQL password
  
)

# Create a cursor
cursor_mysql= conn.cursor()

# Create database
cursor_mysql.execute("CREATE DATABASE IF NOT EXISTS Secure_check;")
print("MySQL database 'Secure_check' created successfully!")

MySQL database 'Secure_check' created successfully!

Table creation

In [185]:
cursor_mysql.execute("USE Secure_check;")
cursor_mysql.execute("""
        create table if not exists traffic_stops  (
                     stop_date DATE NOT NULL,
                     stop_time DATE NOT NULL,
                     country_name VARCHAR(50),
                     driver_gender VARCHAR(10),
                     driver_age INT,
                     driver_race VARCHAR(50),
                     violation VARCHAR(100),
                     search_conducted BOOLEAN,
                     search_type VARCHAR(100),
                     stop_outcome VARCHAR(100),
                     is_arrested BOOLEAN,
                     stop_duration VARCHAR(20),
                     drugs_related_stop BOOLEAN,
                     vehicle_number VARCHAR(15)
                     ); 
                     """)

ADDING THE NEW CREATED COLOUMN TIMESTAMP INTO THE TABLE

In [175]:
cursor_mysql.execute("ALTER TABLE traffic_stops ADD COLUMN timestamp DATETIME;")

In [180]:
print(df['timestamp'].head())

0   2020-01-01 00:00:00
1   2020-01-01 00:01:00
2   2020-01-01 00:02:00
3   2020-01-01 00:03:00
4   2020-01-01 00:04:00
Name: timestamp, dtype: datetime64[ns]

converted timestamp col to datetime datatype

In [179]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [187]:
cursor_mysql.execute("ALTER TABLE traffic_stops MODIFY COLUMN stop_time TIME;")
conn.commit()

In [189]:
print(df.columns.tolist())

['stop_date', 'stop_time', 'country_name', 'driver_gender', 'driver_age', 'driver_race', 'violation', 'search_conducted', 'search_type', 'stop_outcome', 'is_arrested', 'stop_duration', 'drugs_related_stop', 'vehicle_number', 'timestamp']

Insert data into the table

In [188]:
insert_query = """
    INSERT INTO traffic_stops (
        stop_date, stop_time, country_name, driver_gender, driver_age,
        driver_race, violation, search_conducted, search_type,
        stop_outcome, is_arrested, stop_duration, drugs_related_stop,
        vehicle_number, timestamp
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

data = [tuple(row) for row in df.to_numpy()]

cursor_mysql.executemany(insert_query, data)
conn.commit()